-- begin UTILITYLIBRARY_STATUS
alter table UTILITYLIBRARY_STATUS add constraint FK_UTILITYLIBRARY_STATUS_ON_TITLE_BOOK foreign key (TITLE_BOOK_ID) references UTILITYLIBRARY_BOOK(ID)^
alter table UTILITYLIBRARY_STATUS add constraint FK_UTILITYLIBRARY_STATUS_ON_STATUS foreign key (STATUS_ID) references SEC_USER(ID)^
create index IDX_UTILITYLIBRARY_STATUS_ON_TITLE_BOOK on UTILITYLIBRARY_STATUS (TITLE_BOOK_ID)^
create index IDX_UTILITYLIBRARY_STATUS_ON_STATUS on UTILITYLIBRARY_STATUS (STATUS_ID)^
-- end UTILITYLIBRARY_STATUS

-- begin UTILITYLIBRARY_AUTHOR
alter table UTILITYLIBRARY_AUTHOR add constraint FK_UTILITYLIBRARY_AUTHOR_ON_TITLE foreign key (TITLE_ID) references UTILITYLIBRARY_BOOK(ID)^
create index IDX_UTILITYLIBRARY_AUTHOR_ON_TITLE on UTILITYLIBRARY_AUTHOR (TITLE_ID)^
-- end UTILITYLIBRARY_AUTHOR
