alter table UTILITYLIBRARY_STATUS add constraint FK_UTILITYLIBRARY_STATUS_ON_STATUS foreign key (STATUS_ID) references SEC_USER(ID);
create index IDX_UTILITYLIBRARY_STATUS_ON_STATUS on UTILITYLIBRARY_STATUS (STATUS_ID);
