alter table UTILITYLIBRARY_STATUS add constraint FK_UTILITYLIBRARY_STATUS_ON_TITLE_BOOK foreign key (TITLE_BOOK_ID) references UTILITYLIBRARY_BOOK(ID);
create index IDX_UTILITYLIBRARY_STATUS_ON_TITLE_BOOK on UTILITYLIBRARY_STATUS (TITLE_BOOK_ID);
