alter table UTILITYLIBRARY_AUTHOR add constraint FK_UTILITYLIBRARY_AUTHOR_ON_TITLE foreign key (TITLE_ID) references UTILITYLIBRARY_BOOK(ID);
create index IDX_UTILITYLIBRARY_AUTHOR_ON_TITLE on UTILITYLIBRARY_AUTHOR (TITLE_ID);
