alter table UTILITYLIBRARY_STATUS add constraint FK_UTILITYLIBRARY_STATUS_ON_USER foreign key (USER_ID) references UTILITYLIBRARY_USER(ID);
create index IDX_UTILITYLIBRARY_STATUS_ON_USER on UTILITYLIBRARY_STATUS (USER_ID);
